### ISSUE TITLE
Hapi-v17 support?

### ISSUE THREAD

**Issue by sfabriece** [desirable-objects/hapi-ending#1]
Any thoughts on adding support for hapi 17?

**Comment by antony** [comment]
Heya @sfabriece yeah I've been considering it, but I haven't managed to migrate any of my apps to v17 yet so I need to understand how it all works :)

**Comment by Y-LyN-10** [comment]
Are you still interested in upgrading hapi-ending to support Hapi v17? I could give it a try :)

**Comment by antony** [comment]
@Y-LyN-10 absolutely! I'd love it if I could get some help. I actually could use this plugin now as I'm using hapi v17 in one of my projects, but haven't had time to fix the plugin to do it!

**Comment by Y-LyN-10** [comment]
So, I have some [progress](https://github.com/Y-LyN-10/hapi-ending/tree/hapi-v17-support) on that! :) 

The demo runs with Hapi v17 and I updated the tests to run with Lab v16. There were some assertions that are not supported anymore (like "deep" or "include"), but made a work-around (definitely needs polishing). 

The only thing I am stuck at are these "Allowed values".  What was your original idea on those, @antony ? The values of .allow() or .valid() are very different things now and I think that the old version of "hapi-ending" works with both, but that's confusing.

**Comment by antony** [comment]
@Y-LyN-10 It's a good question! I'd have to have a look at a PR to know. Do you have the code in a reviewable state?

**Comment by Y-LyN-10** [comment]
Yes, I will open a PR. There is just one test (related to "Allowed values") that doesn't pass right now.

**Comment by antony** [comment]
Great! I look forward to it.

**Comment by Y-LyN-10** [comment]
Do you want to create a new branch, so the PR will not be into _master_, @antony ? Perhaps, you want to keep the current version for older versions of Hapi.

**Comment by antony** [comment]
I not sure it matters as I don't intend to maintain the existing version,
so the current tag will always be available for existing users wanting to
inspect the source.

**Comment by antony** [comment]
Closed in [https://github.com/desirable-objects/hapi-ending/pull/2]! Thanks @Y-LyN-10 !

**Comment by antony** [comment]
@Y-LyN-10 I've added you as a collaborator to the repo so you don't have to wait for me to review your changes - it's clear that you know what you are doing!

**Comment by Y-LyN-10** [comment]
Thank you, @antony! ❤
