### ISSUE TITLE
description instead of describe

### ISSUE THREAD

**Issue by fallanic** [desirable-objects/hapi-ending#10]
Hi there,

Thanks for the cool plugin, it works out of the box :)

Just wanted to tell people I needed to use`.description('This is where you put the number of As')` instead of `.describe('This is where you put the number of As')` to make the Joi description work.

Not sure if it's a library version problem (Hapi or Joi), just wanted to share :)

Thanks!

**Comment by antony** [comment]
Whoops! My bad :) Fixed now.
