### ISSUE TITLE
Switch from lab to mocha

### ISSUE THREAD

**Issue by antony** [desirable-objects/hapi-ending#7]

**Comment by Y-LyN-10** [comment]
What is your motive for such switch, @antony? Isn't it better to stick to the _hapi ecosystem_? :slightly_smiling_face:

**Comment by antony** [comment]
@Y-LyN-10 shortly after I wrote this plugin I had raised some issues with Lab regarding the way it operated. It turned out that actually Lab was really only designed as an internal tool and wasn't designed to fulfil the needs of the masses.

So I switched a few projects to mocha and honestly, I think it's a better tool overall :)

**Comment by antony** [comment]
As part of this I decided to refactor the tests to perform one assertion per test. I was pretty new to node when I wrote this plugin so my practices weren't great!

Hopefully issues will be much easier to track down and fix now, since https://github.com/desirable-objects/hapi-ending/commit/f13b7f0950d51ef59d970cd7bb58aa9581631c99
